
package jframes;

//Librería para ponerle música al juego
import akinatordisney.MetodosArbolAdivinador;
import java.applet.AudioClip;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author María Zapata y Mateo Peralta
 * Este es el Frame inicial del juego. A partir de ella podemos acceder a cualquier
 *otro Frame del mismo. Los Frames del juego son: JFGame(Frame para jugar);
 *JFRules(Para que el usuario vea las reglas del juego), JFLeaderBoards(Para ver 
 * los records, JFDatosAkiantor(Para visualizar el dibujo del árbol y el archivo;
 * además de esta mismo Frame.)
 */
public class JFInicio extends javax.swing.JFrame {
    AudioClip hola=java.applet.Applet.newAudioClip(getClass().getResource("/pictures/holaAmigos.wav"));
              
    public static String usuario;
    MetodosArbolAdivinador a = new MetodosArbolAdivinador();
    String nom = "", t = "", f = "";

    public JFInicio() throws IOException {
        initComponents();
        //Le pone el icono de la aplicación
        this.setIconImage(new ImageIcon(getClass().getResource
        ("/pictures/mickeyIcon.png")).getImage());
         hola.play();
        imagenes();
        //Pone la pantalla en la mitad
        this.setLocationRelativeTo(null);
    }
    //Métodos
    /**Método para poner la imagen de fondo y que está se adapte al JFrame*/
    public void imagenes() {
        ImageIcon imagen = new ImageIcon(getClass()
        .getResource("/pictures/mickey.gif"));
        Icon icono = new ImageIcon(imagen.
        getImage().getScaledInstance(lbMickey.
         getWidth(), lbMickey.getHeight(), Image.SCALE_DEFAULT));
        lbMickey.setIcon(icono);
         ImageIcon imagen2 = new ImageIcon(getClass()
        .getResource("/pictures/mickey2.gif"));
        Icon icono2 = new ImageIcon(imagen2.
        getImage().getScaledInstance(lbFondo.
         getWidth(), lbFondo.getHeight(), Image.SCALE_DEFAULT));
        lbFondo.setIcon(icono2);
        ImageIcon imagen3 = new ImageIcon(getClass()
        .getResource("/pictures/pergamino.png"));
        Icon icono3 = new ImageIcon(imagen3.
        getImage().getScaledInstance(pergamino.
         getWidth(), pergamino.getHeight(), Image.SCALE_DEFAULT));
        pergamino.setIcon(icono3);
        this.repaint();
    }

    /**Recorremos cada caracter de la cadena y comprobamos si son letras.
        Para comprobarlo, lo pasamos a mayúscula y vemos su numero ASCII.
        Si está fuera del rango 65 - 90, es que no son letras.
        Y la letra ñ es la 165*/
    boolean soloLetras(String cad) {
        for (int i = 0; i < cad.length(); i++) {
            char car = cad.toUpperCase().charAt(i);
            int valASCII = (int) car;
            if (valASCII != 165 && (valASCII < 65 || valASCII > 90)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbMickey = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbProgram = new javax.swing.JLabel();
        linea2 = new javax.swing.JLabel();
        lbScores = new javax.swing.JLabel();
        lbRules = new javax.swing.JLabel();
        lbPlay = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pergamino = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mateo P & María Z.");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(161, 122, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Disney Akinator!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, -1));
        jPanel1.add(lbMickey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbProgram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/candado32.png"))); // NOI18N
        lbProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProgramMouseClicked(evt);
            }
        });
        jPanel2.add(lbProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 260, -1));

        linea2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/linea.png"))); // NOI18N
        jPanel2.add(linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 310, 10));

        lbScores.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        lbScores.setText("     SCORES");
        lbScores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbScores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbScoresMouseClicked(evt);
            }
        });
        jPanel2.add(lbScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 170, -1));

        lbRules.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        lbRules.setText("      RULES");
        lbRules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRulesMouseClicked(evt);
            }
        });
        jPanel2.add(lbRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 150, -1));

        lbPlay.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        lbPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlay.setText("       PLAY");
        lbPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });
        jPanel2.add(lbPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, -1));

        txtUsuario.setBackground(new java.awt.Color(219, 160, 70));
        txtUsuario.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Dígite aquí su nombre de usuario");
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, 24));
        txtUsuario.getAccessibleContext().setAccessibleName("");

        pergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pergamino.png"))); // NOI18N
        jPanel2.add(pergamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 510));
        jPanel2.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        //NOTA: Este textField tiene la propiedad de autoScrowls. Esta propiedad
        //sirve para que mientras el usuario va escribiendo, si la palabra es muy larga,
        //pueda rodarse el texto y seguir viendo lo que escribe
        //ESte comando sirve para cuando el usuario oprime Enter, transfiere el
        //focus a la siguiente componente
        txtUsuario.transferFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
          //Aquí se válida que el nombre de usuario sean sólo letras y sea de máximo
        //7
        hola.stop();
        usuario = txtUsuario.getText();
        try {
            if (usuario.length() <= 7 && usuario.length() > 0  ) {
                if (soloLetras(usuario)) {
                    JFGame p = new JFGame();
                    p.setVisible(true);
                    //Este comando es para que en el momento que se abra esa pantalla, se

                    File file = new File("datosAkinator.txt");
                    //Crea el archivo
                    BufferedReader in = new BufferedReader(new FileReader(file));
                    String line = in.readLine();
                    line = line.substring(2);
                    line = line.split("\\|")[0];
                    //Coloca la primera pregunta del archivo en el label Pregunta
                    this.dispose();
                    //cierre la pantalla en la que estan
                } else {
                     JOptionPane.showMessageDialog(null, "El nombre de usuario"
                            + " sólo puede contener letras sin carácteres especiales"
                             + "y debe ser de máximo "
                            + "7 carácteres.", "Hey amiguito", 0,
          new javax.swing.ImageIcon(getClass().getResource("/Pictures/mickey32.png")) );
                    txtUsuario.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El nombre de usuario debe "
                        + " ser de máximo 7 carácteres, y sólo puede contener "
                        + "letras sin carácteres especiales.", "Hey amiguito", 0,
          new javax.swing.ImageIcon(getClass().getResource("/Pictures/mickey32.png")) );
                txtUsuario.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            txtUsuario.setText("");
        }
    }//GEN-LAST:event_lbPlayMouseClicked

    private void lbRulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRulesMouseClicked
        JFRules p = new JFRules();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        hola.stop();
        this.dispose();
    }//GEN-LAST:event_lbRulesMouseClicked

    private void lbScoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbScoresMouseClicked
        hola.stop();
        JFLeaderboards p = null;
        try {
            p = new JFLeaderboards();
        } catch (IOException ex) {
            Logger.getLogger(JFInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setVisible(true);
        //Este comando es para que en el momento que se abra esa pantalla, se
        //cierre la pantalla en la que estamos
        this.dispose();
    }//GEN-LAST:event_lbScoresMouseClicked

    private void lbProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProgramMouseClicked
         String usuario = txtUsuario.getText();
        if (usuario.equals("datos2")) {
            JFDatosAkinator j = new JFDatosAkinator();
            j.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Esta sección es sólo para"
                    + " programadores :(", "Hey amiguito", 0,
          new javax.swing.ImageIcon(getClass().getResource("/Pictures/mickey32.png")));
        }
    }//GEN-LAST:event_lbProgramMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFInicio().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFInicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbMickey;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbProgram;
    private javax.swing.JLabel lbRules;
    private javax.swing.JLabel lbScores;
    private javax.swing.JLabel linea2;
    private javax.swing.JLabel pergamino;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
