
package jframes;

import AppPackage.AnimationClass;
import akinatordisney.MetodosArbolAdivinador;
import java.applet.AudioClip;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author María Zapata y Mateo Peralta
 * Este Frame es para que el usuario pueda saber en qué consiste el juego
 */
public class JFRules extends javax.swing.JFrame {

     MetodosArbolAdivinador met = new MetodosArbolAdivinador();
     AudioClip audioReglas=java.applet.Applet.newAudioClip(getClass().getResource("/pictures/audioReglas.wav"));
    /**
     * Creates new form JFRules
     */
    public JFRules() {
        initComponents();
        //Le pone el icono de la aplicación
        this.setIconImage(new ImageIcon(getClass().getResource
        ("/pictures/mickeyIcon.png")).getImage());
        imagenes();
        //Pone la pantalla en la mitad
        this.setLocationRelativeTo(null);
       
            audioReglas.play();
     }
    public void imagenes()
    {
       ImageIcon imagen = new ImageIcon(getClass().getResource("/pictures/fondo2.png"));
       Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(lbFondo.getWidth(), lbFondo.getHeight(),Image.SCALE_DEFAULT));
       lbFondo.setIcon(icono);
       this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbMickey = new javax.swing.JLabel();
        lbMulti = new javax.swing.JLabel();
        lbCopa = new javax.swing.JLabel();
        lbRules = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mateo P. & María Z.");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mago2.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 330, 330));

        lbMickey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mickey32.png"))); // NOI18N
        lbMickey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMickey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMickeyMouseClicked(evt);
            }
        });
        jPanel2.add(lbMickey, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 70, 30, 30));

        lbMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/multiMenu.png"))); // NOI18N
        lbMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMultiMouseClicked(evt);
            }
        });
        jPanel2.add(lbMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        lbCopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/copa32.png"))); // NOI18N
        lbCopa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCopa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCopaMouseClicked(evt);
            }
        });
        jPanel2.add(lbCopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 150, -1, 40));

        lbRules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/reiniciar32.png"))); // NOI18N
        lbRules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRulesMouseClicked(evt);
            }
        });
        jPanel2.add(lbRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pergaminoReglas1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 510, 540));

        lbFondo.setBackground(new java.awt.Color(0, 255, 255));
        lbFondo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, 596));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMickeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMickeyMouseClicked
        try {
            JFInicio inicio= new JFInicio();
            this.dispose();
            inicio.setSize(1010, 580);
            inicio.setLocationRelativeTo(null);
            inicio.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(JFRules.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbMickeyMouseClicked

    private void lbMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMultiMouseClicked
        //Derecha
        AnimationClass mickey= new AnimationClass();
        mickey.jLabelXRight(-30, 10, 10, 5, lbMickey);

        AnimationClass music= new AnimationClass();
        music.jLabelXRight(-30, 10, 10, 5, lbRules);

        AnimationClass copa= new AnimationClass();
        copa.jLabelXRight(-30, 10, 10, 5, lbCopa);

        //Izquierda
        AnimationClass mickeyy= new AnimationClass();
        mickeyy.jLabelXLeft(10, -30, 10, 5, lbMickey);

        AnimationClass musicc= new AnimationClass();
        musicc.jLabelXLeft(10, -30, 10, 5, lbRules);

        AnimationClass copaa= new AnimationClass();
        copaa.jLabelXLeft(10, -30, 10, 5, lbCopa);

    }//GEN-LAST:event_lbMultiMouseClicked

    private void lbCopaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCopaMouseClicked

        try {
            JFLeaderboards scores = new JFLeaderboards();
            this.dispose();
            scores.setLocationRelativeTo(null);
            scores.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(JFRules.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lbCopaMouseClicked

    private void lbRulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRulesMouseClicked
            JFRules r= new JFRules();
            this.dispose();
            r.setLocationRelativeTo(null);
            r.setVisible(true);

    }//GEN-LAST:event_lbRulesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCopa;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbMickey;
    private javax.swing.JLabel lbMulti;
    private javax.swing.JLabel lbRules;
    // End of variables declaration//GEN-END:variables
}
